# Generated by Django 4.2 on 2023-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentpost_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.IntegerField()),
                ('user_followed', models.CharField(max_length=100)),
            ],
        ),
    ]
