# Generated by Django 4.2 on 2023-05-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_followeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerUser',
        ),
    ]
