# Generated by Django 4.2 on 2023-05-23 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
