# Generated by Django 4.2 on 2023-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_commentpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagesize',
            field=models.CharField(blank=True, null=True),
        ),
    ]
