# Generated by Django 4.2 on 2023-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_no_of_followers_profile_no_of_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followeruser',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='followeruser',
            name='user_followed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_of_followers',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='no_of_following',
            field=models.BigIntegerField(default=0),
        ),
    ]
