# Generated by Django 4.2 on 2023-06-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_followeruser_follower_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerUser',
        ),
    ]
