# Generated by Django 4.2 on 2023-06-07 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_followeruser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowerUser',
            new_name='FollowerModel',
        ),
    ]
