# Generated by Django 4.2 on 2023-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_followeruser_followermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation_catgory',
            field=models.CharField(default='technology'),
        ),
    ]
