# Generated by Django 4.2 on 2023-06-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_occupation_catgory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation_catgory',
            field=models.CharField(choices=[('Technology', 'technology'), ('Education', 'education'), ('Healthcare', 'healthcare'), ('Government', 'government'), ('Fashion', 'fashion'), ('Science', 'science'), ('Engineering', 'engineering'), ('Sports', 'sports'), ('Finance', 'finance'), ('Security', 'security'), ('Religious', 'religious'), ('Business', 'business'), ('Miscallenous', 'miscallenous')], default='technology'),
        ),
    ]
