# Generated by Django 4.2 on 2023-06-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_occupation_catgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='occupation_catgory',
            new_name='occupation_category',
        ),
    ]
