# Generated by Django 4.2 on 2023-06-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_occupation_catgory_profile_occupation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation_category',
            field=models.CharField(choices=[('Technology', 'technology'), ('Science', 'science'), ('Engineering', 'engineering'), ('Fashion', 'fashion'), ('Sports', 'sports'), ('Entertainment', 'entertainment'), ('Education', 'education'), ('Healthcare', 'healthcare'), ('Government', 'government'), ('Finance', 'finance'), ('Security', 'security'), ('Religious', 'religious'), ('Business', 'business'), ('Miscallenous', 'miscallenous')], default='technology'),
        ),
    ]
