# Generated by Django 4.2 on 2023-05-09 00:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(default=True, max_length=50, null=True)),
                ('bio', models.TextField(default='i am a cribspace user', null=True)),
                ('image', models.ImageField(upload_to='post-images')),
                ('occupation', models.CharField(default='cribspace user', max_length=50, null=True)),
                ('caption', models.TextField(default=True, max_length=900, null=True)),
                ('no_of_likes', models.BigIntegerField(default=0)),
                ('no_of_comments', models.BigIntegerField(default=0)),
            ],
        ),
    ]
