# Generated by Django 4.2 on 2023-05-09 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-post.jpg', upload_to='post-images'),
        ),
    ]
