# Generated by Django 4.1.7 on 2023-03-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='this is an empty bio', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='somewhere,earth', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='cribspace user', max_length=50, null=True),
        ),
    ]
