# Generated by Django 4.2 on 2023-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
