# Generated by Django 4.2 on 2023-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='content',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='title',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
