# Generated by Django 4.1.7 on 2023-04-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.BigIntegerField(default='0000000000', null=True),
        ),
    ]
