# Generated by Django 4.2 on 2023-05-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0004_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='defaullt.jpg', upload_to='profile_images'),
        ),
    ]
