# Generated by Django 4.2 on 2023-05-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0005_alter_profile_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
