# Generated by Django 4.2 on 2023-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifcations',
            name='notif_type',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notifcations',
            name='other_user',
            field=models.IntegerField(default=0),
        ),
    ]
