# Generated by Django 4.2 on 2023-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifcations_notif_type_notifcations_other_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifcations',
            name='other_data',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
